export const MAX_SKILL_ARCHIVE_BYTES = 12 * 1024 * 1024;
export const MAX_SKILL_MULTIPART_ENVELOPE_BYTES = 1024 * 1024;
export const MAX_PRODUCTION_REQUEST_BODY_BYTES =
  MAX_SKILL_ARCHIVE_BYTES + MAX_SKILL_MULTIPART_ENVELOPE_BYTES;
